Deduplicate an import
tool `flake8` did report
 test_fancybox.py:13:1: F811 redefinition of unused 'fancybox_plugin'
 from line 8
so the other one might also get removed.